package com.example.ui.theme

import androidx.compose.ui.graphics.Color

// --- Fresh Green ---
val FreshGreenPrimary = Color(0xFF386B01)
val FreshGreenOnPrimary = Color(0xFFFFFFFF)
val FreshGreenPrimaryContainer = Color(0xFFB8F397)
val FreshGreenOnPrimaryContainer = Color(0xFF0D2000)
val FreshGreenSecondary = Color(0xFF55624C)
val FreshGreenOnSecondary = Color(0xFFFFFFFF)
val FreshGreenSecondaryContainer = Color(0xFFD9E7CB)
val FreshGreenOnSecondaryContainer = Color(0xFF131F0E)
val FreshGreenBackground = Color(0xFFFDFDF6)
val FreshGreenOnBackground = Color(0xFF1A1C18)
val FreshGreenSurface = Color(0xFFFDFDF6)
val FreshGreenOnSurface = Color(0xFF1A1C18)
val FreshGreenSurfaceVariant = Color(0xFFE0E4D6)
val FreshGreenOnSurfaceVariant = Color(0xFF44483D)
val FreshGreenOutline = Color(0xFF74796C)

val FreshGreenPrimaryDark = Color(0xFF9DD67D)
val FreshGreenOnPrimaryDark = Color(0xFF1B3700)
val FreshGreenPrimaryContainerDark = Color(0xFF295000)
val FreshGreenOnPrimaryContainerDark = Color(0xFFB8F397)
val FreshGreenSecondaryDark = Color(0xFFBDCBB0)
val FreshGreenOnSecondaryDark = Color(0xFF283421)
val FreshGreenSecondaryContainerDark = Color(0xFF3E4A36)
val FreshGreenOnSecondaryContainerDark = Color(0xFFD9E7CB)
val FreshGreenBackgroundDark = Color(0xFF1A1C18)
val FreshGreenOnBackgroundDark = Color(0xFFE2E3DE)
val FreshGreenSurfaceDark = Color(0xFF1A1C18)
val FreshGreenOnSurfaceDark = Color(0xFFE2E3DE)
val FreshGreenSurfaceVariantDark = Color(0xFF44483D)
val FreshGreenOnSurfaceVariantDark = Color(0xFFC4C8BA)

// --- Sky Blue ---
val SkyBluePrimary = Color(0xFF0061A4)
val SkyBlueOnPrimary = Color(0xFFFFFFFF)
val SkyBluePrimaryContainer = Color(0xFFD1E4FF)
val SkyBlueOnPrimaryContainer = Color(0xFF001D36)
val SkyBlueSecondary = Color(0xFF535F70)
val SkyBlueOnSecondary = Color(0xFFFFFFFF)
val SkyBlueSecondaryContainer = Color(0xFFD7E3F7)
val SkyBlueOnSecondaryContainer = Color(0xFF101C2B)
val SkyBlueBackground = Color(0xFFFDFCFF)
val SkyBlueOnBackground = Color(0xFF1A1C1E)
val SkyBlueSurface = Color(0xFFFDFCFF)
val SkyBlueOnSurface = Color(0xFF1A1C1E)
val SkyBlueOutline = Color(0xFF73777F)

val SkyBluePrimaryDark = Color(0xFF9ECAFF)
val SkyBlueOnPrimaryDark = Color(0xFF003258)
val SkyBluePrimaryContainerDark = Color(0xFF00497D)
val SkyBlueOnPrimaryContainerDark = Color(0xFFD1E4FF)
val SkyBlueSecondaryDark = Color(0xFFBBC7DB)
val SkyBlueOnSecondaryDark = Color(0xFF253140)
val SkyBlueSecondaryContainerDark = Color(0xFF3B4858)
val SkyBlueOnSecondaryContainerDark = Color(0xFFD7E3F7)
val SkyBlueBackgroundDark = Color(0xFF1A1C1E)
val SkyBlueOnBackgroundDark = Color(0xFFE2E2E6)
val SkyBlueSurfaceDark = Color(0xFF1A1C1E)
val SkyBlueOnSurfaceDark = Color(0xFFE2E2E6)

// --- Elegant Purple ---
val ElegantPurplePrimary = Color(0xFF6750A4)
val ElegantPurpleOnPrimary = Color(0xFFFFFFFF)
val ElegantPurplePrimaryContainer = Color(0xFFEADDFF)
val ElegantPurpleOnPrimaryContainer = Color(0xFF21005D)
val ElegantPurpleSecondary = Color(0xFF625B71)
val ElegantPurpleOnSecondary = Color(0xFFFFFFFF)
val ElegantPurpleSecondaryContainer = Color(0xFFE8DEF8)
val ElegantPurpleOnSecondaryContainer = Color(0xFF1D192B)
val ElegantPurpleBackground = Color(0xFFFFFBFE)
val ElegantPurpleOnBackground = Color(0xFF1C1B1F)
val ElegantPurpleSurface = Color(0xFFFFFBFE)
val ElegantPurpleOnSurface = Color(0xFF1C1B1F)
val ElegantPurpleOutline = Color(0xFF79747E)

val ElegantPurplePrimaryDark = Color(0xFFD0BCFF)
val ElegantPurpleOnPrimaryDark = Color(0xFF381E72)
val ElegantPurplePrimaryContainerDark = Color(0xFF4F378B)
val ElegantPurpleOnPrimaryContainerDark = Color(0xFFEADDFF)
val ElegantPurpleSecondaryDark = Color(0xFFCCC2DC)
val ElegantPurpleOnSecondaryDark = Color(0xFF332D41)
val ElegantPurpleSecondaryContainerDark = Color(0xFF4A4458)
val ElegantPurpleOnSecondaryContainerDark = Color(0xFFE8DEF8)
val ElegantPurpleBackgroundDark = Color(0xFF1C1B1F)
val ElegantPurpleOnBackgroundDark = Color(0xFFE6E1E5)
val ElegantPurpleSurfaceDark = Color(0xFF1C1B1F)
val ElegantPurpleOnSurfaceDark = Color(0xFFE6E1E5)

// --- Vibrant Orange ---
val VibrantOrangePrimary = Color(0xFF8B5000)
val VibrantOrangeOnPrimary = Color(0xFFFFFFFF)
val VibrantOrangePrimaryContainer = Color(0xFFFFDCBE)
val VibrantOrangeOnPrimaryContainer = Color(0xFF2D1600)
val VibrantOrangeSecondary = Color(0xFF715A41)
val VibrantOrangeOnSecondary = Color(0xFFFFFFFF)
val VibrantOrangeSecondaryContainer = Color(0xFFFDDABE)
val VibrantOrangeOnSecondaryContainer = Color(0xFF281805)
val VibrantOrangeBackground = Color(0xFFFFFBFF)
val VibrantOrangeOnBackground = Color(0xFF201A17)
val VibrantOrangeSurface = Color(0xFFFFFBFF)
val VibrantOrangeOnSurface = Color(0xFF201A17)
val VibrantOrangeOutline = Color(0xFF827568)

val VibrantOrangePrimaryDark = Color(0xFFFFB870)
val VibrantOrangeOnPrimaryDark = Color(0xFF4A2800)
val VibrantOrangePrimaryContainerDark = Color(0xFF693B00)
val VibrantOrangeOnPrimaryContainerDark = Color(0xFFFFDCBE)
val VibrantOrangeSecondaryDark = Color(0xFFDFC2A2)
val VibrantOrangeOnSecondaryDark = Color(0xFF402D17)
val VibrantOrangeSecondaryContainerDark = Color(0xFF58422B)
val VibrantOrangeOnSecondaryContainerDark = Color(0xFFFDDABE)
val VibrantOrangeBackgroundDark = Color(0xFF201A17)
val VibrantOrangeOnBackgroundDark = Color(0xFFEBE0DB)
val VibrantOrangeSurfaceDark = Color(0xFF201A17)
val VibrantOrangeOnSurfaceDark = Color(0xFFEBE0DB)

// --- Sakura Pink ---
val SakuraPinkPrimary = Color(0xFF9C4146)
val SakuraPinkOnPrimary = Color(0xFFFFFFFF)
val SakuraPinkPrimaryContainer = Color(0xFFFFDAD9)
val SakuraPinkOnPrimaryContainer = Color(0xFF40000A)
val SakuraPinkSecondary = Color(0xFF775656)
val SakuraPinkOnSecondary = Color(0xFFFFFFFF)
val SakuraPinkSecondaryContainer = Color(0xFFFFDAD9)
val SakuraPinkOnSecondaryContainer = Color(0xFF2C1516)
val SakuraPinkBackground = Color(0xFFFFFBFF)
val SakuraPinkOnBackground = Color(0xFF201A1A)
val SakuraPinkSurface = Color(0xFFFFFBFF)
val SakuraPinkOnSurface = Color(0xFF201A1A)
val SakuraPinkOutline = Color(0xFF857373)

val SakuraPinkPrimaryDark = Color(0xFFFFB3B4)
val SakuraPinkOnPrimaryDark = Color(0xFF5F121C)
val SakuraPinkPrimaryContainerDark = Color(0xFF7D2930)
val SakuraPinkOnPrimaryContainerDark = Color(0xFFFFDAD9)
val SakuraPinkSecondaryDark = Color(0xFFE7BDBE)
val SakuraPinkOnSecondaryDark = Color(0xFF44292A)
val SakuraPinkSecondaryContainerDark = Color(0xFF5D3F3F)
val SakuraPinkOnSecondaryContainerDark = Color(0xFFFFDAD9)
val SakuraPinkBackgroundDark = Color(0xFF201A1A)
val SakuraPinkOnBackgroundDark = Color(0xFFECE0DF)
val SakuraPinkSurfaceDark = Color(0xFF201A1A)
val SakuraPinkOnSurfaceDark = Color(0xFFECE0DF)
